import fs from 'node:fs';
import path from 'node:path';

import { logStep, writeFile } from './lib/mapper-utils';

const MOUNT_ROOT = 'src/mount';

const WIZARD_APP_STUB_MARKER = 'WIZARD_APP_STUB';
const TIMELINE_APP_STUB_MARKER = 'TIMELINE_APP_STUB';
const WIZARD_PAGE_STUB_MARKER = 'WIZARD_PAGE_STUB';
const ROUTE_PAGE_STUB_MARKER = 'ROUTE_PAGE_STUB';

function resetDir() {
  logStep('Очистка каталога монтирования');
  // Preserve AGENTS.md — generated by frida:gen, not a mapper artifact
  const agentsPath = path.join(MOUNT_ROOT, 'AGENTS.md');
  const agentsContent = fs.existsSync(agentsPath)
    ? fs.readFileSync(agentsPath, 'utf-8')
    : null;

  fs.rmSync(MOUNT_ROOT, { recursive: true, force: true });

  // Restore AGENTS.md after wipe
  if (agentsContent) {
    fs.mkdirSync(MOUNT_ROOT, { recursive: true });
    fs.writeFileSync(agentsPath, agentsContent, 'utf-8');
  }
}

function createWizardAppStub() {
  writeFile(
    `${MOUNT_ROOT}/wizard/App.tsx`,
    `// ${WIZARD_APP_STUB_MARKER}
import React from 'react';

export interface WizardAppProps {
  onComplete?: (routeId: string) => void;
  onError?: (error: Error) => void;
}

const WizardAppStub: React.FC<WizardAppProps> = () => {
  throw new Error('STUB: WizardApp не смонтирован. Запустите npm run mapper:all');
};

export default WizardAppStub;
`,
  );
}

function createTimelineAppStub() {
  writeFile(
    `${MOUNT_ROOT}/timeline/App.tsx`,
    `// ${TIMELINE_APP_STUB_MARKER}
import React from 'react';

export interface TimelineAppProps {
  routeId: string;
  onSave?: () => Promise<{ token: string }>;
  onShare?: (token: string) => void;
  onReset?: () => void;
}

const TimelineAppStub: React.FC<TimelineAppProps> = () => {
  throw new Error('STUB: TimelineApp не смонтирован. Запустите npm run mapper:all');
};

export default TimelineAppStub;
`,
  );
}

function createWizardPageStub() {
  writeFile(
    `${MOUNT_ROOT}/pages/WizardPage.tsx`,
    `// ${WIZARD_PAGE_STUB_MARKER}
import React from 'react';
import WizardApp from '@/mount/wizard/App';

export const WizardPage: React.FC = () => <WizardApp />;

export default WizardPage;
`,
  );
}

function createRoutePageStub() {
  writeFile(
    `${MOUNT_ROOT}/pages/RoutePage.tsx`,
    `// ${ROUTE_PAGE_STUB_MARKER}
import React from 'react';

export const RoutePage: React.FC = () => <div>Route Page Stub</div>;

export default RoutePage;
`,
  );
}

function createIndexes() {
  writeFile(
    `${MOUNT_ROOT}/pages/index.ts`,
    `export { default as WizardPage } from './WizardPage';
export { default as RoutePage } from './RoutePage';
`,
  );

  writeFile(
    `${MOUNT_ROOT}/index.ts`,
    `export * from './pages';
`,
  );
}

resetDir();
logStep('Восстановление заглушек для mapper mount');
createWizardAppStub();
createTimelineAppStub();
createWizardPageStub();
createRoutePageStub();
createIndexes();

console.log('✅ Состояние /src/mount сброшено к заглушкам');
