import fs from 'node:fs';
import { ensureDirectory, logStep, writeFile, copyDir } from '../lib/mapper-utils';
import { applyMotoTheme } from './styler-timeline';


// --- RESET LOGIC ---
if (process.argv.includes('--reset')) {
  logStep('♻️ RESET: Reverting Timeline to Stub');
  const OUTPUT_DIR = 'src/mount/timeline';
  const TIMELINE_PATH = 'src/pages/RoutePage/Timeline.tsx';
  if (fs.existsSync(TIMELINE_PATH)) {
    const stubContent = `import React from 'react';
import { TimelineAppProps } from '@/mount/timeline/types';

const TimelineApp: React.FC<TimelineAppProps> = () => {
    return (
        <div className="flex items-center justify-center h-screen bg-slate-900 text-slate-500">
            Timeline Stub
        </div>
    );
};

export default TimelineApp;
`;
    writeFile(TIMELINE_PATH, stubContent);
    logStep('✅ Timeline.tsx restored to local stub');
  }

  if (fs.existsSync(OUTPUT_DIR)) {
    fs.rmSync(OUTPUT_DIR, { recursive: true, force: true });
    logStep(`✅ Cleaned ${OUTPUT_DIR}`);
  }

  console.log('🏁 Timeline reset complete');
  process.exit(0);
}
// -------------------

const SOURCE_DIR = 'dist/aistudio/timeline';
const OUTPUT_DIR = 'src/mount/timeline';

logStep('Копирование зависимостей timeline');
ensureDirectory(OUTPUT_DIR);
copyDir(`${SOURCE_DIR}/components`, `${OUTPUT_DIR}/components`);

// --- STEP 1: Generate contract ComplexityBadge (numeric complexity) ---
logStep('Генерация канонического ComplexityBadge (numeric complexity 1-10)');
const contractBadgeContent = `import React from 'react';

interface Props {
  complexity: number; // 1-10
  size?: 'sm' | 'md';
}

function getComplexityInfo(complexity: number): { colorClass: string; label: string } {
  if (complexity <= 3) {
    return { colorClass: 'bg-[#9CA3AF]/20 text-[#9CA3AF] border-[#9CA3AF]/30', label: 'Easy' };
  }
  if (complexity <= 5) {
    return { colorClass: 'bg-[#60A5FA]/20 text-[#60A5FA] border-[#60A5FA]/30', label: 'Moderate' };
  }
  if (complexity <= 7) {
    return { colorClass: 'bg-[#3B82F6]/20 text-[#3B82F6] border-[#3B82F6]/30', label: 'Hard' };
  }
  return { colorClass: 'bg-[#8B5CF6]/20 text-[#8B5CF6] border-[#8B5CF6]/30', label: 'Extreme' };
}

const ComplexityBadge: React.FC<Props> = ({ complexity, size = 'md' }) => {
  const { colorClass, label } = getComplexityInfo(complexity);
  const sizeClass = size === 'sm' ? 'text-xs px-2 py-0.5' : 'text-sm px-3 py-1';

  return (
    <span className={\`inline-flex items-center justify-center rounded-full border \${colorClass} \${sizeClass} font-medium\`}>
      {label} ({complexity})
    </span>
  );
};

export default ComplexityBadge;
`;
writeFile(`${OUTPUT_DIR}/components/ComplexityBadge.tsx`, contractBadgeContent);

// --- STEP 2: Generate contract types.ts ---
logStep('Генерация канонических типов (contract:DATABASE_SCHEMA)');
const contractTypesContent = `// Contract Timeline Types - generated by surgeon-timeline.ts
// Source: contract:DATABASE_SCHEMA.route_assembly

export type WaypointType = 'origin' | 'destination' | 'road-junction';

export interface ContractWaypoint {
  id: string;
  type: WaypointType;
  lat: number;
  lng: number;
  title_ru: string;
  hint_ru?: string;
  anchor?: { anchorPartIndex: number };
}

export type SegmentKind = 'monotonous_highway' | 'urban_navigation' | 'cruise'
  | 'twisty_forest' | 'serious_serpentine' | 'nav';

export interface ContractSegment {
  segment_index: number;
  from_lat: number;
  from_lng: number;
  to_lat: number;
  to_lng: number;
  road_ref?: string;
  title_ru: string;
  distance_km: number;
  beauty: number;        // 1-10
  complexity: number;    // 1-10
  kind: SegmentKind;
  turniness: number;     // 0-1
  decision_density: number; // 0-1
}

export interface RouteSummary {
  distance_km: number;
  duration_min: number;
}

export type LoadingStage = 'skeleton' | 'waypoints' | 'descriptions' | 'ready' | 'error';

export interface TimelineAppProps {
  // Data (from RoutePage host)
  waypoints: ContractWaypoint[];
  segments: ContractSegment[];
  summary: RouteSummary | null;

  // Loading state (host manages polling)
  loadingStage: LoadingStage;
  errorMessage?: string;

  // Selection sync (timeline -> map via host)
  onWaypointSelect?: (waypointId: string | null) => void;
  onSegmentSelect?: (segmentIndex: number | null) => void;

  // Actions (host provides handlers)
  onRetry?: () => void;
}
`;
writeFile(`${OUTPUT_DIR}/types.ts`, contractTypesContent);

// --- STEP 3: Generate contract App.tsx ---
logStep('Генерация канонического TimelineApp (props-driven, no Map/routeService)');

// Generate the TimelineApp component preserving visual DNA from AI Studio
// but using contract types and props-driven architecture
let appContent = generateContractTimelineApp();

// Apply moto theme colors (orange accent, neutral darks)
appContent = applyMotoTheme(appContent);

writeFile(`${OUTPUT_DIR}/App.tsx`, appContent);
console.log(`✅ Результат surgery сохранён в ${OUTPUT_DIR}/App.tsx`);

// --- STEP 4: Mount in Timeline.tsx ---
logStep('Монтирование таймлайна в Timeline.tsx');
const TIMELINE_PATH = 'src/pages/RoutePage/Timeline.tsx';
const mountContent = `import TimelineApp from '@/mount/timeline/App';
export default TimelineApp;
`;
writeFile(TIMELINE_PATH, mountContent);
console.log(`✅ Таймлайн смонтирован в ${TIMELINE_PATH} (через re-export)`);

// === TEMPLATE GENERATOR ===

function generateContractTimelineApp(): string {
  return `import React, { useState } from 'react';
import {
  MapPin,
  Navigation,
  ChevronDown,
  ChevronUp,
  Circle,
  ChevronsDown,
  Loader2,
} from 'lucide-react';
import {

  ContractWaypoint,
  ContractSegment,
  SegmentKind,
  TimelineAppProps,
} from './types';
import ComplexityBadge from './components/ComplexityBadge';

// --- HELPERS ---

function getComplexityColor(complexity: number): string {
  if (complexity <= 3) return 'bg-[#9CA3AF]';
  if (complexity <= 5) return 'bg-[#60A5FA]';
  if (complexity <= 7) return 'bg-[#3B82F6]';
  return 'bg-[#8B5CF6]';
}

function getKindLabel(kind: SegmentKind): string {
  switch (kind) {
    case 'monotonous_highway': return 'Highway';
    case 'urban_navigation': return 'Urban';
    case 'cruise': return 'Cruise';
    case 'twisty_forest': return 'Twisty';
    case 'serious_serpentine': return 'Serpentine';
    case 'nav': return 'Navigation';
    default: return kind;
  }
}

// --- COMPONENT ---

function TimelineApp({
  waypoints,
  segments,
  summary,
  loadingStage,
  errorMessage,
  onWaypointSelect,
  onSegmentSelect,
  onRetry,
}: TimelineAppProps) {
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const toggleExpand = (id: string) => {
    setExpandedId(prev => (prev === id ? null : id));
  };

  const handleWaypointClick = (wp: ContractWaypoint) => {
    toggleExpand(wp.id);
    onWaypointSelect?.(expandedId === wp.id ? null : wp.id);
  };

  const handleSegmentClick = (seg: ContractSegment) => {
    const segId = \`segment-\${seg.segment_index}\`;
    toggleExpand(segId);
    onSegmentSelect?.(expandedId === segId ? null : seg.segment_index);
  };

  // Auto-scroll to selected item
  React.useEffect(() => {
    if (!expandedId) return;
    const el = document.querySelector(\`[data-item-id="\${expandedId}"]\`);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
  }, [expandedId]);

  // --- RENDER: Waypoint ---
  const renderWaypoint = (wp: ContractWaypoint) => {
    const isExpanded = expandedId === wp.id;
    const isOrigin = wp.type === 'origin';
    const isDestination = wp.type === 'destination';

    return (
      <div
        key={wp.id}
        data-item-id={wp.id}
        className="relative z-10"
      >
        <div
          onClick={() => handleWaypointClick(wp)}
          className={\`
            relative z-20 flex items-center p-2 -ml-2 rounded-xl transition-all duration-300 cursor-pointer
            \${isExpanded ? 'bg-slate-800 shadow-lg border border-slate-700/50 scale-[1.02]' : 'hover:bg-slate-800/50'}
          \`}
        >
          {/* Icon Circle */}
          <div className={\`
            flex items-center justify-center w-10 h-10 rounded-full border-4 shadow-sm shrink-0
            \${isOrigin ? 'bg-blue-500 border-slate-900 text-white' : ''}
            \${isDestination ? 'bg-slate-100 border-slate-900 text-slate-900' : ''}
            \${!isOrigin && !isDestination ? 'bg-slate-700 border-slate-900 text-slate-300' : ''}
          \`}>
            {isOrigin && <Navigation size={16} />}
            {isDestination && <MapPin size={16} fill="currentColor" />}
            {!isOrigin && !isDestination && <Circle size={12} fill="currentColor" />}
          </div>

          {/* Label */}
          <div className="ml-4 flex-1">
            <div className="flex items-baseline justify-between">
              <h3 className="text-lg font-bold text-slate-100">{wp.title_ru}</h3>
            </div>
            {!isExpanded && (
              <p className="text-xs text-slate-400 uppercase tracking-wider">{wp.type}</p>
            )}
          </div>

          <div className="ml-2 text-slate-500">
            {isExpanded ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
          </div>
        </div>

        {/* Expanded Detail */}
        {isExpanded && (
          <div className="mt-2 mb-6 -mx-2 bg-slate-900/90 rounded-xl border border-slate-700/50 backdrop-blur-md shadow-xl animate-in fade-in slide-in-from-top-2 overflow-hidden z-20">
            <div className="p-3">
              <div className="text-sm text-slate-300 space-y-1">
                {wp.hint_ru && <p className="text-slate-400">{wp.hint_ru}</p>}
                <p className="text-xs text-slate-500 font-mono">
                  {wp.lat.toFixed(4)}, {wp.lng.toFixed(4)}
                </p>
              </div>
            </div>
          </div>
        )}
      </div>
    );
  };

  // --- RENDER: Segment ---
  const renderSegment = (seg: ContractSegment) => {
    const segId = \`segment-\${seg.segment_index}\`;
    const isExpanded = expandedId === segId;
    const lineColor = getComplexityColor(seg.complexity);

    return (
      <div key={segId} data-item-id={segId} className={\`relative pl-3 py-2 group\`}>
        {/* Vertical Connection Line */}
        <div className={\`absolute left-[1.15rem] top-0 bottom-0 w-1.5 \${lineColor} rounded-full opacity-60 group-hover:opacity-100 transition-opacity\`}></div>

        {/* Segment Card */}
        <div className="relative pl-8 pr-1">
          <div
            onClick={() => handleSegmentClick(seg)}
            className={\`
              cursor-pointer overflow-hidden transition-all duration-300 border
              \${isExpanded
                ? 'bg-slate-800 border-slate-600 rounded-2xl shadow-xl scale-[1.02] my-4'
                : 'bg-slate-900/40 border-slate-800 rounded-lg hover:bg-slate-800/60 my-1'}
            \`}
          >
            <div className="p-4">
              {/* Header row */}
              <div className="flex justify-between items-start mb-2">
                {!isExpanded && (
                  <ComplexityBadge complexity={seg.complexity} size="sm" />
                )}
                <div className="flex items-center gap-2 text-slate-400 text-xs font-mono ml-auto">
                  <ChevronsDown size={14} />
                  <span>{seg.distance_km.toFixed(1)} km</span>
                </div>
              </div>

              {/* Title */}
              <div className="relative">
                <p className={\`text-slate-300 leading-relaxed \${!isExpanded ? 'line-clamp-2 text-sm' : 'text-base'}\`}>
                  {seg.title_ru}
                </p>
                {!isExpanded && seg.title_ru.length > 80 && (
                  <div className="absolute inset-0 bg-gradient-to-r from-transparent via-transparent to-slate-900/20"></div>
                )}
              </div>

              {/* Expanded Details */}
              {isExpanded && (
                <div className="mt-4 space-y-3 pt-4 border-t border-slate-700/50">
                  {/* Complexity Badge */}
                  <div className="flex items-center gap-3">
                    <ComplexityBadge complexity={seg.complexity} />
                    <span className="text-xs text-slate-500 uppercase font-bold tracking-wider">
                      {getKindLabel(seg.kind)}
                    </span>
                  </div>

                  {/* Metrics Grid */}
                  <div className="grid grid-cols-2 gap-3">
                    <div className="bg-slate-900/60 rounded-lg p-2.5">
                      <div className="text-[10px] text-slate-500 uppercase font-bold mb-1">Beauty</div>
                      <div className="text-slate-200 font-mono text-sm">{seg.beauty}/10</div>
                    </div>
                    <div className="bg-slate-900/60 rounded-lg p-2.5">
                      <div className="text-[10px] text-slate-500 uppercase font-bold mb-1">Complexity</div>
                      <div className="text-slate-200 font-mono text-sm">{seg.complexity}/10</div>
                    </div>
                    <div className="bg-slate-900/60 rounded-lg p-2.5">
                      <div className="text-[10px] text-slate-500 uppercase font-bold mb-1">Turniness</div>
                      <div className="text-slate-200 font-mono text-sm">{(seg.turniness * 100).toFixed(0)}%</div>
                    </div>
                    <div className="bg-slate-900/60 rounded-lg p-2.5">
                      <div className="text-[10px] text-slate-500 uppercase font-bold mb-1">Decisions</div>
                      <div className="text-slate-200 font-mono text-sm">{(seg.decision_density * 100).toFixed(0)}%</div>
                    </div>
                  </div>

                  {/* Road ref */}
                  {seg.road_ref && (
                    <div className="text-xs text-slate-500 font-mono">{seg.road_ref}</div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  };

  // --- RENDER: Loading / Error States ---

  if (loadingStage === 'error') {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-slate-950 text-slate-200 p-8">
        <div className="text-red-400 text-sm mb-4 text-center">
          {errorMessage || 'Error loading route'}
        </div>
        {onRetry && (
          <button
            onClick={onRetry}
            className="px-6 py-3 bg-red-900/50 hover:bg-red-900 border border-red-700 rounded-lg text-red-200 text-sm font-medium transition-all hover:scale-105"
          >
            Retry
          </button>
        )}
      </div>
    );
  }

  if (loadingStage === 'skeleton') {
    // Skeleton stage: show origin/destination placeholders
    const origin = waypoints.find(w => w.type === 'origin');
    const destination = waypoints.find(w => w.type === 'destination');

    return (
      <div className="min-h-screen bg-slate-950 text-slate-200">
        <div className="max-w-md mx-auto p-4 pt-6">
          <div className="relative">
            {/* Wavy placeholder line */}
            <svg
              className="absolute left-[1.15rem] top-10 w-3"
              style={{ height: 'calc(100% - 5rem)' }}
              viewBox="0 0 12 200"
              preserveAspectRatio="none"
            >
              <path
                d="M 6 0 Q 12 25, 6 50 Q 0 75, 6 100 Q 12 125, 6 150 Q 0 175, 6 200"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeDasharray="6 4"
                strokeLinecap="round"
                className="text-slate-500/60"
              />
            </svg>

            {/* Origin */}
            <div className="relative z-10 flex items-center p-2 -ml-2">
              <div className="flex items-center justify-center w-10 h-10 rounded-full border-4 bg-blue-500 border-slate-900 text-white shadow-lg">
                <Navigation size={16} />
              </div>
              <div className="ml-4 flex-1">
                <h3 className="text-lg font-bold text-slate-100">{origin?.title_ru || 'Origin'}</h3>
                <p className="text-xs text-slate-400 uppercase tracking-wider">origin</p>
              </div>
            </div>

            {/* Loading indicator */}
            <div className="relative z-10 py-16 pl-12">
              <div className="flex flex-col items-center justify-center">
                <div className="flex items-center gap-3 mb-3">
                  <div className="flex gap-1.5">
                    <div className="w-2.5 h-2.5 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                    <div className="w-2.5 h-2.5 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                    <div className="w-2.5 h-2.5 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                  </div>
                </div>
                <div className="text-slate-400 text-sm">Building route...</div>
              </div>
            </div>

            {/* Destination */}
            <div className="relative z-10 flex items-center p-2 -ml-2">
              <div className="flex items-center justify-center w-10 h-10 rounded-full border-4 bg-slate-100 border-slate-900 text-slate-900 shadow-lg">
                <MapPin size={16} fill="currentColor" />
              </div>
              <div className="ml-4 flex-1">
                <h3 className="text-lg font-bold text-slate-100">{destination?.title_ru || 'Destination'}</h3>
                <p className="text-xs text-slate-400 uppercase tracking-wider">destination</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // --- RENDER: Main Timeline (waypoints / descriptions / ready) ---

  // For 'waypoints' stage, segments may be empty or partial
  const showDescriptions = loadingStage === 'descriptions' || loadingStage === 'ready';

  return (
    <div className="min-h-screen pb-20 bg-slate-950 text-slate-200">
      <main className="max-w-md mx-auto p-4 pt-2">
        <div className="relative">
          {/* Continuous vertical line background guide */}
          <div className="absolute left-[1.325rem] top-4 bottom-4 w-[1px] bg-slate-800 -z-0"></div>

          {waypoints.map((wp, index) => {
            const seg = segments.find(s => s.segment_index === index);


            return (
              <React.Fragment key={wp.id}>
                {renderWaypoint(wp)}
                {seg && showDescriptions && renderSegment(seg)}
                {seg && !showDescriptions && (
                  <div className="relative pl-3 py-2">
                    <div className={\`absolute left-[1.15rem] top-0 bottom-0 w-1.5 bg-slate-600 rounded-full opacity-40\`}></div>
                    <div className="relative pl-8 pr-1">
                      <div className="bg-slate-900/40 border border-slate-800 rounded-lg p-3 my-1">
                        <div className="flex items-center gap-2 text-slate-500 text-xs">
                          <div className="h-2 w-16 bg-slate-800 rounded animate-pulse"></div>
                          <span className="ml-auto font-mono">{seg.distance_km.toFixed(1)} km</span>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </React.Fragment>
            );
          })}

          {/* Loading indicator for incomplete stages */}
          {loadingStage === 'waypoints' && (
            <div className="flex items-center justify-center py-4 gap-2 text-slate-500 text-xs">
              <Loader2 size={14} className="animate-spin" />
              <span>Loading segment details...</span>
            </div>
          )}
          {loadingStage === 'descriptions' && (
            <div className="flex items-center justify-center py-4 gap-2 text-slate-500 text-xs">
              <Loader2 size={14} className="animate-spin" />
              <span>Loading descriptions...</span>
            </div>
          )}
        </div>

        {/* Summary bar */}
        {summary && (
          <div className="mt-6 bg-slate-900/60 border border-slate-800 rounded-xl p-4">
            <div className="flex items-center justify-between text-sm">
              <div className="flex items-center gap-1 text-slate-400">
                <span className="font-mono text-slate-200">{summary.distance_km.toFixed(0)}</span>
                <span>km</span>
              </div>
              <div className="h-3 w-px bg-slate-700" />
              <div className="flex items-center gap-1 text-slate-400">
                <span className="font-mono text-slate-200">{summary.duration_min}</span>
                <span>min</span>
              </div>
              <div className="h-3 w-px bg-slate-700" />
              <div className="flex items-center gap-1 text-slate-400">
                <span className="font-mono text-slate-200">{waypoints.length}</span>
                <span>waypoints</span>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

export default TimelineApp;
`;
}
